# Base image
FROM archlinux:latest

# Install dependencies
RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
    base-devel \
    git \
    meson \
    ninja \
    python \
    python-pip \
    libdrm \
    libgbm \
    libx11 \
    libxext \
    libxdamage \
    libxfixes \
    libxcb \
    xcb-util \
    libxxf86vm \
    zlib \
    wget \
    curl

# Clone Mesa repository
RUN git clone https://gitlab.freedesktop.org/mesa/mesa.git /mesa

# Set working directory
WORKDIR /mesa