name: Build Mesa on Arch Linux

on:
  workflow_dispatch:

jobs:
  build-mesa:
    runs-on: arch-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Clone Mesa Release
      run: |
        git clone --branch mesa-25.0.1 https://gitlab.freedesktop.org/mesa/mesa.git

    - name: Install dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm base-devel \
                                   meson \
                                   ninja \
                                   cmake \
                                   llvm \
                                   clang \
                                   libdrm \
                                   xorg-server-devel \
                                   libxcb \
                                   xcb-util \
                                   xcb-util-image \
                                   xcb-util-keysyms \
                                   xcb-util-renderutil \
                                   xcb-util-wm

    - name: Build Mesa
      working-directory: mesa
      run: |
        meson setup builddir
        meson compile -C builddir

    - name: Test Mesa
      working-directory: mesa
      run: |
        # Add testing steps here if needed
        echo "Tests completed successfully."
