name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test Docker Containers
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, fedora-latest, archlinux-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for ${{ matrix.os }}
        run: |
          docker build -f Dockerfile.${{ matrix.os }} -t mesa-ps4-${{ matrix.os }} .

      - name: Run Container for ${{ matrix.os }}
        run: |
          docker run --rm mesa-ps4-${{ matrix.os }} /mesa/build_mesa.sh
