name: Build Mesa on Fedora

on:
  workflow_dispatch:

jobs:
  build-mesa:
    runs-on: fedora-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Clone Mesa Release
      run: |
        git clone --branch mesa-25.0.1 https://gitlab.freedesktop.org/mesa/mesa.git

    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y @development-tools \
                            meson \
                            ninja-build \
                            cmake \
                            llvm \
                            clang \
                            libdrm-devel \
                            xorg-x11-server-devel \
                            libxcb-devel \
                            xcb-util-devel \
                            xcb-util-image-devel \
                            xcb-util-keysyms-devel \
                            xcb-util-renderutil-devel \
                            xcb-util-wm-devel

    - name: Build Mesa
      working-directory: mesa
      run: |
        meson setup builddir
        meson compile -C builddir

    - name: Test Mesa
      working-directory: mesa
      run: |
        # Add testing steps here if needed
        echo "Tests completed successfully."
