name: Build Mesa on Ubuntu

on:
  workflow_dispatch:

jobs:
  build-and-cache-spirv:
    runs-on: ubuntu-latest
    name: Build and Cache SPIRV-Tools

    steps:
      - name: Cache SPIRV-Tools
        id: cache-spirv
        uses: actions/cache@v4
        with:
          path: ~/spirv-tools-install
          key: spirv-tools-v1-20240412

      - name: Cache APT packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt/lists
          key: apt-cache-v1

      - name: Build SPIRV-Tools if not cached
        if: steps.cache-spirv.outputs.cache-hit != 'true'
        run: |
          sudo apt update
          sudo apt install -y cmake python3 git g++ pkg-config

          git clone https://github.com/KhronosGroup/SPIRV-Tools.git --recursive
          cd SPIRV-Tools
          python3 utils/git-sync-deps
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/spirv-tools-install
          make -j$(nproc)
          make install

      - name: Verify SPIRV-Tools install
        run: |
          find ~/spirv-tools-install
          ls ~/spirv-tools-install/bin

      - name: Fetch latest Mesa release tag
        id: fetch-latest-release
        run: |
          latest_tag=$(curl -s "https://gitlab.freedesktop.org/api/v4/projects/176/repository/tags" | jq -r '.[0].name')
          echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

      - name: Cache Mesa repository
        id: cache-mesa
        uses: actions/cache@v4
        with:
          path: ./mesa
          key: mesa-repo-${{ env.LATEST_TAG }}

      - name: Clone Mesa repository if not cached
        if: steps.cache-mesa.outputs.cache-hit != 'true'
        run: |
          git clone --recursive https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          git checkout $LATEST_TAG

  build-mesa-ps4:
    needs: build-and-cache-spirv
    runs-on: ubuntu-latest
    name: Build Mesa and Components for PS4

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Enable source repositories
        run: |
          source /etc/os-release
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://azure.archive.ubuntu.com/ubuntu $VERSION_CODENAME-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          echo "deb-src http://security.ubuntu.com/ubuntu $VERSION_CODENAME-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
          sudo apt update

      - name: Install dependencies
        run: |
            sudo apt build-dep mesa -y
            sudo apt install -y \
            build-essential \
            glslang-tools \
            libelf-dev \
            liblua5.4-dev \
            libclang-17-dev \
            clang-tools-17 \
            libclc-dev \
            libclang-17-dev \
            libclang-cpp19 \
            libudev-dev \
            libvdpau1 \
            libunwind-dev \
            llvm-17-dev \
            llvm-spirv-17 \
            spirv-tools \
            libllvmspirvlib-19-dev \
            bindgen \
            meson-1.5 \
            ninja-build \
            python3-pip \
            python3-setuptools \
            python3-mako \
            libdrm-dev \
            libgbm-dev \
            libegl-dev \
            libgles2-mesa-dev \
            libwayland-dev \
            libwayland-egl-backend-dev \
            wayland-protocols \
            libxcb-randr0-dev \
            xorg-dev \
            xserver-xorg-dev \
            libpciaccess-dev \
            autoconf \
            automake \
            libtool
            zstd

      - name: Restore SPIRV-Tools cache
        uses: actions/cache@v4
        with:
          path: ~/spirv-tools-install
          key: spirv-tools-v1-20240412

      - name: Set environment paths for SPIRV-Tools
        run: |
          echo "$HOME/spirv-tools-install/bin" >> $GITHUB_PATH
          echo "CMAKE_PREFIX_PATH=$HOME/spirv-tools-install" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$HOME/spirv-tools-install/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
   
      - name: Restore Mesa repository cache
        id: restore-mesa
        uses: actions/cache@v4
        with:
          path: ./mesa
          key: mesa-repo-${{ env.LATEST_TAG }}

      - name: Copy patch
        working-directory: ./patches
        run: |
          cp mesa.patch ../mesa
          cp libdrm.patch ../mesa/libdrm
          cp xf86-video-amdgpu.patch ../mesa
# Removed patch  -Np1 < mesa.patch for now
      - name: Build Mesa
        working-directory: ./mesa
        run: |
          mkdir build64
          meson setup build64 -Dplatforms=x11,wayland -Dgallium-extra-hud=true -Dvulkan-drivers=amd,swrast,virtio -Dgallium-drivers=radeonsi,r600,zink,virgl,softpipe,llvmpipe -Dshader-cache=enabled -Dvulkan-layers=device-select,overlay,screenshot -Dopengl=true -Dgles1=enabled -Dgles2=enabled -Degl=enabled -Dllvm=enabled -Dlmsensors=enabled -Dtools=glsl,nir -Dgallium-vdpau=enabled -Dgallium-va=enabled -Dglvnd=enabled -Dgbm=enabled -Dlibunwind=enabled -Dosmesa=true -Dgallium-nine=true -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc,av1dec,av1enc,vp9dec -Dlegacy-x11=dri2 -Dteflon=true -Dzstd=enabled -Dspirv-to-dxil=true -Dshader-cache-max-size=8G -Dstatic-libclc=all --buildtype=plain -Db_ndebug=true -Dc_args=-pipe -Dcpp_args=-std=c++17 -Dvalgrind=enabled -Dgallium-rusticl=true
          ninja -C build64

      - name: Compress build64 directory
        working-directory: ./mesa
        run: |
          tar -I 'zstd -19 -T0' -cf ../mesa-build64.tar.zst build64

      - name: Upload mesa-build64.tar.zst as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesa-build64
          path: mesa-build64.tar.zst
          
      # Step 7: Build xf86-video-amdgpu for PS4
      #- name: Build xf86-video-amdgpu
       # run: |
        #  patch  -Np1 < ../patches/xf86-video-amdgpu.patch
         # cd xf86-video-amdgpu
          #./autogen.sh --prefix=/usr
          #make
          #sudo make install
          #cd ../..
