name: Build Mesa on Ubuntu

on:
  workflow_dispatch:

jobs:
  build-mesa-ps4:
    name: Build Mesa and Components for PS4
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            meson \
            ninja-build \
            python3-pip \
            python3-setuptools \
            python3-mako \
            libdrm-dev \
            libgbm-dev \
            libegl-dev \
            libgles2-mesa-dev \
            libwayland-dev \
            wayland-protocols \
            xorg-dev \
            xserver-xorg-dev \
            libpciaccess-dev \
            autoconf \
            automake \
            libtool

      - name: Clone Mesa
        run: |
          git clone --recursive https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          # Fetch the latest Mesa release tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latest_tag

      - name: Copy patch
        working-directory: ./patches
        run: |
          cp mesa.patch ../mesa
          cp libdrm.patch ../mesa/libdrm
          cp xf86-video-amdgpu.patch ../mesa

# Removed patch  -Np1 < mesa.patch for now
      - name: Build Mesa
        working-directory: ./mesa
        run: |
          mkdir -p build64
          cd build64
          meson setup build64 \
          -D b_ndebug=true \
          -D b_lto=true \
          -D buildtype=plain \
          --wrap-mode=nofallback \
          -D prefix=/usr \
          -D sysconfdir=/etc \
          --libdir=/usr/x86_64 \
          -D platforms=x11,wayland \
          -D gallium-drivers=kmsro,radeonsi,r300,r600,nouveau,freedreno,swrast,v3d,vc4,etnaviv,tegra,i915,svga,virgl,panfrost,iris,lima,zink,d3d12,asahi,crocus \
          -D vulkan-drivers=amd,swrast,intel \
          -D dri3=enabled \
          -D egl=enabled \
          -D gallium-extra-hud=true \
          -D gallium-nine=true \
          -D gallium-omx=bellagio \
          -D gallium-va=enabled \
          -D gallium-vdpau=enabled \
          -D gallium-xa=enabled \
          -D gallium-omx=disabled \
          -D gbm=enabled \
          -D gles1=disabled \
          -D gles2=enabled \
          -D glvnd=true \
          -D glx=dri \
          -D libunwind=enabled \
          -D llvm=enabled \
          -D lmsensors=enabled \
          -D osmesa=true \
          -D shared-glapi=enabled \
          -D gallium-opencl=icd \
          -D valgrind=disabled \
          -D vulkan-layers=device-select,overlay \
          -D tools=[] \
          -D zstd=enabled \
          -D microsoft-clc=disabled \
          meson configure build64
          ninja "{$NINJAFLAGS}" -C build64

          
      # Step 4: Build and install libdrm for PS4
      - name: Build and install libdrm
        working-directory: ./mesa
        run: |
          cd libdrm
          patch  -Np1 < libdrm.patch
          .meson setup build64 \
          --prefix /usr \
          --libdir x86_64 \
          --buildtype plain \
          --wrap-mode      nofallback \
          -D udev=false \
          -D valgrind=disabled \
          -D intel=enabled
          meson configure build64
          ninja -C build64

      # Step 7: Build xf86-video-amdgpu for PS4
      #- name: Build xf86-video-amdgpu
       # run: |
        #  patch  -Np1 < ../patches/xf86-video-amdgpu.patch
         # cd xf86-video-amdgpu
          #./autogen.sh --prefix=/usr
          #make
          #sudo make install
          #cd ../..
