name: Build Mesa and Components for PS4 Ubuntu

on:
  workflow_dispatch:

jobs:
  build-mesa-ps4:
    name: Build Mesa and Components for PS4
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Clone Mesa
        run: |
          git clone --recursive https://gitlab.freedesktop.org/mesa/mesa.git
          cd mesa
          # Fetch the latest Mesa release tag
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $latest_tag
          cd ..

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            meson \
            ninja-build \
            python3-pip \
            python3-setuptools \
            python3-mako \
            libdrm-dev \
            libgbm-dev \
            libegl-dev \
            libgles2-mesa-dev \
            libwayland-dev \
            wayland-protocols \
            xorg-dev \
            xserver-xorg-dev \
            libpciaccess-dev \
            autoconf \
            automake \
            libtool
        
        - name: Apply patches
        run: |
          cd patches
          cp *.patch ../mesa
          cd ../mesa
          git apply mesa.patch
          git apply libdrm.patch
          git apply xf86-video-amdgpu.patch

      # Step 4: Build and install libdrm for PS4
      - name: Build and install libdrm
        run: |
          cd libdrm
          ./autogen.sh --prefix=/usr
          make
          sudo make install
          cd ../..

      # Step 6: Build Mesa for PS4
      - name: Build Mesa
        run: |
          cd mesa
          mkdir -p build
          cd build
          meson --prefix=/usr -Dplatforms=drm -Ddri-drivers= -Dvulkan-drivers= -Dgallium-drivers=radeonsi,svga,swrast ..
          ninja
          sudo ninja install
          cd ../..

      # Step 7: Build xf86-video-amdgpu for PS4
      - name: Build xf86-video-amdgpu
        run: |
          cd PS4Linux-ArchDrivers/SRC/xf86-video-amdgpu-ps4
          ./autogen.sh --prefix=/usr
          make
          sudo make install
          cd ../..
